# Generated by Django 4.2.5 on 2023-09-17 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название товара')),
                ('price', models.PositiveIntegerField(verbose_name='цена(KZT)')),
                ('category', models.CharField(choices=[('HM', 'Для дома'), ('CLTHS', 'Одежда'), ('SCHL', 'Школа'), ('DCH', 'Дача'), ('KDSFR', 'Для детей'), ('DCTN', 'Образование')], default='Не указано', max_length=10, verbose_name='категория')),
                ('description', models.TextField(verbose_name='описание')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
                'ordering': ('title',),
            },
        ),
    ]
